# 公共配置文件
server:
  port: 8090
spring:
  # 默认 dev 环境
  profiles:
    active: dev
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, derder
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: dubbo-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848